import Img from "@/components/html/img";
import ScreenSizeIndicator from "@/components/screen-size-indicator";
import Footer from "@/components/sections/footer";
import { env } from "@/env";
import "@/styles/globals.css";
import rectangle_left from "assets/rectangle-left-bg-logo.png";
import rectangle_right from "assets/rectangle-right-bg-logo.png";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

type Props = { children: React.ReactNode };

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ru">
      <body className="bg-white font-lato">
        {env.NODE_ENV === "development" ? <ScreenSizeIndicator /> : null}

        <main className="relative">
          {children}

          <section className="font-bold font-nitti text-center absolute top-12 left-12">
            <h1 className="text-9xl">23</h1>
            <p className="text-4xl">Стандарт</p>
          </section>

          <Img src={rectangle_left} className="absolute bottom-0 left-0 w-56" alt="" />
          <Img src={rectangle_right} className="absolute top-0 right-0 w-56" alt="" />

          <Footer />
        </main>
      </body>
    </html>
  );
}
